services:
  db:
    container_name: "pulseDB"
    image: postgres:18-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: pulse
      POSTGRES_PASSWORD: pulse_pwd
      POSTGRES_DB: pulse_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data:rw
      - /etc/localtime:/etc/localtime:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pulse -d pulse_db"]
      interval: 15s
      timeout: 5s
      retries: 3

#/var/lib/postgresql/data
#/var/lib/postgresql/18/docker
volumes:
  db_data:



